### ISSUE TITLE
@ensure

### ISSUE THREAD

**Issue by orsinium** [life4/deal#11]
Combination of `@pre` and `@post`. 

1. Called after function call
2. asses args, kwargs and `result` keyword argument with function result.
3. Raises `PostConditionError` on contract violation.

That's `@post` that can use data from function arguments.

Example:

```python
@deal.ensure(lambda a, b, result: abs(a) < abs(b) or abs(result) >= 1)
@deal.ensure(lambda a, b, result: abs(a) >= (b) or result < 1)
def div(a, b):
  return a / b
```

**Comment by spencerwi** [comment]
I can do this one.
