### ISSUE TITLE
Multi-run properties.

### ISSUE THREAD

**Issue by orsinium** [life4/deal#32]
Some really useful properties can be described only by a few calls of the function. A few examples:

```python
reverse(reverse(x)) == x
sum(a, b + 1) == sum(a, b) + 1
```

In other words, we need to do an additional function call to check the property. While it's ok for pure and fast functions, in other cases (and we have them a lot in python) such behavior can be really painful. So, how to check contract with such properties?

**Comment by orsinium** [comment]
@sobolevn I need your advice.

**Comment by sobolevn** [comment]
Sorry, I am out of the context. What's the initial idea behind this issue?

**Comment by orsinium** [comment]
The idea is we want to be able to implement any property as a contract. All existing contract runs when the function is called, and just check input and output values, and side-effects in the process. However, it's not enough when you must do one more function call to check the property. If we'll do it implicitly, it can be unintuitive and raise long debugging why the function was called twice. As an option, we can run these properties only in special tests, but then it can raise a question why the contract wasn't tested in runtime. 

And also one more difference for such contracts from other: we can't check it statically at all, it's too complicated. However, it's not a big deal.

**Comment by orsinium** [comment]
There is no good way to check it at runtime or statically, they can be checked only in tests. So, the best place for them is tests.

```python
@pytest.mark.parametrize('case', deal.cases(reverse))
def test_div(case: deal.TestCase) -> None:
    case()
    reverse(reverse(**case.kwargs)) == case.kwargs['x']
```
