### ISSUE TITLE
deal usage with frozen class

### ISSUE THREAD

**Issue by galen104** [life4/deal#42]
I want to add validation with `deal` to a frozen class:

```
@attr.s(auto_attribs=True, frozen=True, slots=True)
class Foo:
    symbol: str = attr.ib()
```

I have already tried with `@deal.inv` but it didn't work.

```
@deal.inv(lambda data: isinstance(data.symbol, str), message='invalid `symbol`')
@attr.s(auto_attribs=True, frozen=True, slots=True)
class Foo:
    symbol: str = attr.ib()

fooInstance = Foo(symbol=1)
```
If I set `frozen=False` the code works.
What is the proper way to do this? 

ps: I known that `attr` has his own validation.

**Comment by orsinium** [comment]
Well, `deal.inv` rewrites class from the ground zero, and `attr.s` does the same. I'm not sure it's even possible to support attrs for the invariant.

**Comment by galen104** [comment]
Thanks for the quick answer, I will use `attr.s` validation for class fields, and `deal`'s one for normal functions.

**Comment by orsinium** [comment]
Great! All other contracts should work as expected :+1:
